[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  [functions.fetchCards]
  path = "netlify/functions/fetchCards.mts"

  [functions.fetchSingleCard]
  path = "netlify/functions/fetchSingleCard.mts"